version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
    container_name: json-server-api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
