version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8080}
    container_name: json-server-api
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
