version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-server-api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
